In [1]:
import numpy as np

In [2]:
v_hor_np = np.array([1, 2])

In [3]:
v_hor_np

array([1, 2])

In [4]:
v_hor_zeros_v1 = np.zeros((5, ))

In [5]:
v_hor_zeros_v1

array([0., 0., 0., 0., 0.])

In [6]:
v_hor_zeros_v2 = np.zeros((1, 5))

In [8]:
v_hor_zeros_v2

array([[0., 0., 0., 0., 0.]])

In [9]:
v_hor_one_v1 = np.ones((5,))

In [10]:
v_hor_one_v1

array([1., 1., 1., 1., 1.])

In [12]:
v_hor_one_v2 = np.ones((1, 5))

In [13]:
v_hor_one_v2

array([[1., 1., 1., 1., 1.]])

In [15]:
v_vert_np = np.array([[1], [2]])

In [16]:
v_vert_np

array([[1],
       [2]])

In [17]:
v_vert_zeros = np.zeros((5, 1))

In [18]:
v_vert_zeros

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [19]:
v_vert_ones = np.ones((5, 1))

In [20]:
v_vert_ones

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [21]:
m_sqr_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [22]:
m_sqr_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
m_sqr_mx = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [24]:
m_sqr_mx

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [25]:
np.matrix("1 2 3; 4 5 6; 7 8 9")

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [26]:
m_sqr_mx = np.matrix('1 2 3; 4 5 6; 7 8 9')

In [27]:
diag = np.diag(m_sqr_mx)

In [28]:
diag

array([1, 5, 9])

In [29]:
m_diag_np = np.diag(diag)

In [30]:
m_diag_np

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [31]:
m_eye = np.eye(3)

In [32]:
m_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
A = np.matrix("1 2 3; 4 5 6")

In [35]:
A_t = A.transpose()

In [36]:
A

matrix([[1, 2, 3],
        [4, 5, 6]])

In [37]:
A_t

matrix([[1, 4],
        [2, 5],
        [3, 6]])

In [38]:
A.T

matrix([[1, 4],
        [2, 5],
        [3, 6]])

In [39]:
A.T.T

matrix([[1, 2, 3],
        [4, 5, 6]])

In [40]:
A = np.matrix('1 2 3; 4 5 6')
B = np.matrix('7 8 9; 0 7 5')

In [41]:
L = (A + B).T
L

matrix([[ 8,  4],
        [10, 12],
        [12, 11]])

In [43]:
R = A.T + B.T
R

matrix([[ 8,  4],
        [10, 12],
        [12, 11]])

In [44]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')

В данном примере, для умножения матриц, использовалась функция *dot()* из библиотеки
Numpy.

In [48]:
L = A.dot(B).T
L

matrix([[19, 43],
        [22, 50]])

In [50]:
R = B.T.dot(A.T)
R

matrix([[19, 43],
        [22, 50]])

In [51]:
A = np.matrix('1 2 3; 4 5 6')
k = 3

In [52]:
L = (k * A).T
L

matrix([[ 3, 12],
        [ 6, 15],
        [ 9, 18]])

In [53]:
R = k * A.T
R

matrix([[ 3, 12],
        [ 6, 15],
        [ 9, 18]])

In [54]:
A = np.matrix('1 2; 3 4')

In [57]:
A_det = np.linalg.det(A)
format(A_det, '.9g')

'-2'

In [58]:
A_T_det = np.linalg.det(A.T)
format(A_T_det, '.9g')

'-2'

In [59]:
A = np.matrix("1 2 3; 4 5 6")
A

matrix([[1, 2, 3],
        [4, 5, 6]])

In [60]:
C = 3 * A
C

matrix([[ 3,  6,  9],
        [12, 15, 18]])

In [61]:
A = np.matrix("1 2; 3 4")
A

matrix([[1, 2],
        [3, 4]])

In [62]:
A * 1

matrix([[1, 2],
        [3, 4]])

In [64]:
A = np.matrix("1 2; 3 4")
A

matrix([[1, 2],
        [3, 4]])

In [65]:
Z = np.matrix("0 0; 0 0")
Z

matrix([[0, 0],
        [0, 0]])

In [66]:
0 * A

matrix([[0, 0],
        [0, 0]])

In [69]:
A = np.matrix("1 2; 3 4")
p = 2
q = 3

In [70]:
L = (p + q) * A
L

matrix([[ 5, 10],
        [15, 20]])

In [71]:
R = p * A + q * A
R

matrix([[ 5, 10],
        [15, 20]])

In [72]:
A = np.matrix("1 2; 3 4")
p = 2
q = 3

In [73]:
L = (p * q) * A
L

matrix([[ 6, 12],
        [18, 24]])

In [75]:
R = p * (q * A)
R

matrix([[ 6, 12],
        [18, 24]])

In [76]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
k = 3

In [77]:
L = k * (A + B)
L

matrix([[18, 24],
        [30, 36]])

In [78]:
R = k * A + k * B
R

matrix([[18, 24],
        [30, 36]])

In [79]:
A = np.matrix('1 6 3; 8 2 7')
B = np.matrix('8 1 5; 6 9 12')

In [80]:
C = A + B
C

matrix([[ 9,  7,  8],
        [14, 11, 19]])

In [81]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')

In [82]:
A + B

matrix([[ 6,  8],
        [10, 12]])

In [83]:
B + A

matrix([[ 6,  8],
        [10, 12]])

In [84]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('1 7; 9 3')

In [85]:
A + (B + C)

matrix([[ 7, 15],
        [19, 15]])

In [86]:
(A + B) + C

matrix([[ 7, 15],
        [19, 15]])

In [87]:
A = np.matrix("1 2; 3 4")

In [89]:
A + -A

matrix([[0, 0],
        [0, 0]])

In [90]:
A = np.matrix('1 2 3; 4 5 6')
B = np.matrix('7 8; 9 1; 2 3')

In [91]:
A.dot(B)

matrix([[31, 19],
        [85, 55]])

In [92]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('2 4; 7 8')

In [93]:
A.dot(B + C)

matrix([[35, 42],
        [77, 94]])

In [94]:
A.dot(B) + A.dot(C)

matrix([[35, 42],
        [77, 94]])

In [95]:
A.dot(B)

matrix([[19, 22],
        [43, 50]])

In [96]:
B.dot(A)

matrix([[23, 34],
        [31, 46]])

In [98]:
E = np.ones((2, 2))
E

array([[1., 1.],
       [1., 1.]])

In [108]:
E = np.diag(np.ones(2))
E

array([[1., 0.],
       [0., 1.]])

In [109]:
A.dot(E)

matrix([[1., 2.],
        [3., 4.]])

In [110]:
E.dot(A)

matrix([[1., 2.],
        [3., 4.]])