In [2]:
import numpy as np

In [3]:
v_hor_np = np.array([1, 2])

In [4]:
v_hor_np

array([1, 2])

In [5]:
v_hor_zeros_v1 = np.zeros((5, ))

In [6]:
v_hor_zeros_v1

array([0., 0., 0., 0., 0.])

In [7]:
v_hor_zeros_v2 = np.zeros((1, 5))

In [8]:
v_hor_zeros_v2

array([[0., 0., 0., 0., 0.]])

In [9]:
v_hor_one_v1 = np.ones((5,))

In [10]:
v_hor_one_v1

array([1., 1., 1., 1., 1.])

In [11]:
v_hor_one_v2 = np.ones((1, 5))

In [12]:
v_hor_one_v2

array([[1., 1., 1., 1., 1.]])

In [13]:
v_vert_np = np.array([[1], [2]])

In [14]:
v_vert_np

array([[1],
       [2]])

In [15]:
v_vert_zeros = np.zeros((5, 1))

In [16]:
v_vert_zeros

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [17]:
v_vert_ones = np.ones((5, 1))

In [18]:
v_vert_ones

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [19]:
m_sqr_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [20]:
m_sqr_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
m_sqr_mx = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [22]:
m_sqr_mx

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [23]:
np.matrix("1 2 3; 4 5 6; 7 8 9")

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [24]:
m_sqr_mx = np.matrix('1 2 3; 4 5 6; 7 8 9')

In [25]:
diag = np.diag(m_sqr_mx)

In [26]:
diag

array([1, 5, 9])

In [27]:
m_diag_np = np.diag(diag)

In [28]:
m_diag_np

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [29]:
m_eye = np.eye(3)

In [30]:
m_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
A = np.matrix("1 2 3; 4 5 6")

In [33]:
A_t = A.transpose()

In [34]:
A

matrix([[1, 2, 3],
        [4, 5, 6]])

In [35]:
A_t

matrix([[1, 4],
        [2, 5],
        [3, 6]])

In [36]:
A.T

matrix([[1, 4],
        [2, 5],
        [3, 6]])

In [37]:
A.T.T

matrix([[1, 2, 3],
        [4, 5, 6]])

In [38]:
A = np.matrix('1 2 3; 4 5 6')
B = np.matrix('7 8 9; 0 7 5')

In [39]:
L = (A + B).T
L

matrix([[ 8,  4],
        [10, 12],
        [12, 11]])

In [40]:
R = A.T + B.T
R

matrix([[ 8,  4],
        [10, 12],
        [12, 11]])

In [41]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')

В данном примере, для умножения матриц, использовалась функция *dot()* из библиотеки
Numpy.

In [42]:
L = A.dot(B).T
L

matrix([[19, 43],
        [22, 50]])

In [43]:
R = B.T.dot(A.T)
R

matrix([[19, 43],
        [22, 50]])

In [44]:
A = np.matrix('1 2 3; 4 5 6')
k = 3

In [45]:
L = (k * A).T
L

matrix([[ 3, 12],
        [ 6, 15],
        [ 9, 18]])

In [46]:
R = k * A.T
R

matrix([[ 3, 12],
        [ 6, 15],
        [ 9, 18]])

In [47]:
A = np.matrix('1 2; 3 4')

In [48]:
A_det = np.linalg.det(A)
format(A_det, '.9g')

'-2'

In [49]:
A_T_det = np.linalg.det(A.T)
format(A_T_det, '.9g')

'-2'

In [50]:
A = np.matrix("1 2 3; 4 5 6")
A

matrix([[1, 2, 3],
        [4, 5, 6]])

In [51]:
C = 3 * A
C

matrix([[ 3,  6,  9],
        [12, 15, 18]])

In [52]:
A = np.matrix("1 2; 3 4")
A

matrix([[1, 2],
        [3, 4]])

In [53]:
A * 1

matrix([[1, 2],
        [3, 4]])

In [54]:
A = np.matrix("1 2; 3 4")
A

matrix([[1, 2],
        [3, 4]])

In [55]:
Z = np.matrix("0 0; 0 0")
Z

matrix([[0, 0],
        [0, 0]])

In [56]:
0 * A

matrix([[0, 0],
        [0, 0]])

In [57]:
A = np.matrix("1 2; 3 4")
p = 2
q = 3

In [58]:
L = (p + q) * A
L

matrix([[ 5, 10],
        [15, 20]])

In [59]:
R = p * A + q * A
R

matrix([[ 5, 10],
        [15, 20]])

In [60]:
A = np.matrix("1 2; 3 4")
p = 2
q = 3

In [61]:
L = (p * q) * A
L

matrix([[ 6, 12],
        [18, 24]])

In [62]:
R = p * (q * A)
R

matrix([[ 6, 12],
        [18, 24]])

In [63]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
k = 3

In [64]:
L = k * (A + B)
L

matrix([[18, 24],
        [30, 36]])

In [65]:
R = k * A + k * B
R

matrix([[18, 24],
        [30, 36]])

In [66]:
A = np.matrix('1 6 3; 8 2 7')
B = np.matrix('8 1 5; 6 9 12')

In [67]:
C = A + B
C

matrix([[ 9,  7,  8],
        [14, 11, 19]])

In [68]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')

In [69]:
A + B

matrix([[ 6,  8],
        [10, 12]])

In [70]:
B + A

matrix([[ 6,  8],
        [10, 12]])

In [71]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('1 7; 9 3')

In [72]:
A + (B + C)

matrix([[ 7, 15],
        [19, 15]])

In [73]:
(A + B) + C

matrix([[ 7, 15],
        [19, 15]])

In [74]:
A = np.matrix("1 2; 3 4")

In [75]:
A + -A

matrix([[0, 0],
        [0, 0]])

In [76]:
A = np.matrix('1 2 3; 4 5 6')
B = np.matrix('7 8; 9 1; 2 3')

In [77]:
A.dot(B)

matrix([[31, 19],
        [85, 55]])

In [78]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('2 4; 7 8')

In [79]:
A.dot(B + C)

matrix([[35, 42],
        [77, 94]])

In [80]:
A.dot(B) + A.dot(C)

matrix([[35, 42],
        [77, 94]])

In [81]:
A.dot(B)

matrix([[19, 22],
        [43, 50]])

In [82]:
B.dot(A)

matrix([[23, 34],
        [31, 46]])

In [83]:
E = np.ones((2, 2))
E

array([[1., 1.],
       [1., 1.]])

In [84]:
E = np.diag(np.ones(2))
E

array([[1., 0.],
       [0., 1.]])

In [85]:
A.dot(E)

matrix([[1., 2.],
        [3., 4.]])

In [86]:
E.dot(A)

matrix([[1., 2.],
        [3., 4.]])

In [88]:
A = np.matrix("1 2; 3 4")
Z = np.zeros((2, 2))

In [89]:
Z.dot(A)

matrix([[0., 0.],
        [0., 0.]])

In [90]:
A.dot(Z)

matrix([[0., 0.],
        [0., 0.]])

In [93]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
A

matrix([[-4, -1,  2],
        [10,  4, -1],
        [ 8,  3,  1]])

In [94]:
np.linalg.det(A)

-14.000000000000009

In [96]:
round(np.linalg.det(A), 3)

-14.0

In [97]:
round(np.linalg.det(A.T), 3)

-14.0

In [99]:
A = np.matrix('-4 -1 2; 0 0 0; 8 3 1')
A

matrix([[-4, -1,  2],
        [ 0,  0,  0],
        [ 8,  3,  1]])

In [100]:
np.linalg.det(A)

0.0

In [105]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
B = np.matrix('10 4 -1; -4 -1 2; 8 3 1')

In [106]:
round(np.linalg.det(A), 3)

-14.0

In [107]:
round(np.linalg.det(B), 3)

14.0

In [108]:
A = np.matrix('-4 -1 2; -4 -1 2; 8 3 1')
A

matrix([[-4, -1,  2],
        [-4, -1,  2],
        [ 8,  3,  1]])

In [109]:
round(np.linalg.det(A), 3)

0.0

In [110]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
A

matrix([[-4, -1,  2],
        [10,  4, -1],
        [ 8,  3,  1]])

In [113]:
B = A.copy()
k = 2
B

matrix([[-4, -1,  2],
        [10,  4, -1],
        [ 8,  3,  1]])

In [114]:
B[2:, ] *= k
B

matrix([[-4, -1,  2],
        [10,  4, -1],
        [16,  6,  2]])

In [115]:
round(np.linalg.det(A), 3)

-14.0

In [116]:
round(np.linalg.det(B), 3)

-28.0

In [122]:
A = np.matrix('-4 -1 2; -4 -1 2; 8 3 1')
B = np.matrix('-4 -1 2; 8 3 2; 8 3 1')
C = A.copy()

In [123]:
C[1, :] += B[1, :]
C

matrix([[-4, -1,  2],
        [ 4,  2,  4],
        [ 8,  3,  1]])

In [124]:
round(np.linalg.det(C), 3)

4.0

In [125]:
round(np.linalg.det(A), 3) + round(np.linalg.det(B), 3)

4.0

In [131]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
A

matrix([[-4, -1,  2],
        [10,  4, -1],
        [ 8,  3,  1]])

In [132]:
k = 2
B = A.copy()

In [133]:
B[1, :] += k * B[0, :]
B

matrix([[-4, -1,  2],
        [ 2,  2,  3],
        [ 8,  3,  1]])

In [134]:
round(np.linalg.det(A), 3)

-14.0

In [135]:
round(np.linalg.det(B), 3)

-14.0

In [141]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
k = 2
A

matrix([[-4, -1,  2],
        [10,  4, -1],
        [ 8,  3,  1]])

In [142]:
A[1, :] = A[0, :] + k * A[2, :]
A

matrix([[-4, -1,  2],
        [12,  5,  4],
        [ 8,  3,  1]])

In [143]:
round(np.linalg.det(A), 3)

0.0

In [145]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
k = 2
A

matrix([[-4, -1,  2],
        [10,  4, -1],
        [ 8,  3,  1]])

In [146]:
A[1, :] = A[0, :] * k
A

matrix([[-4, -1,  2],
        [-8, -2,  4],
        [ 8,  3,  1]])

In [147]:
round(np.linalg.det(A), 3)

0.0

In [148]:
A = np.matrix("1 -3; 2 5")
A

matrix([[ 1, -3],
        [ 2,  5]])

In [150]:
A_inv = np.linalg.inv(A)
A_inv

matrix([[ 0.45454545,  0.27272727],
        [-0.18181818,  0.09090909]])

In [152]:
np.linalg.inv(A_inv)

matrix([[ 1., -3.],
        [ 2.,  5.]])

In [153]:
np.linalg.inv(A.T)

matrix([[ 0.45454545, -0.18181818],
        [ 0.27272727,  0.09090909]])

In [154]:
np.linalg.inv(A).T

matrix([[ 0.45454545, -0.18181818],
        [ 0.27272727,  0.09090909]])

In [155]:
A = np.matrix('1. -3.; 2. 5.')
B = np.matrix('7. 6.; 1. 8.')

In [156]:
np.linalg.inv(A.dot(B))

matrix([[ 0.09454545,  0.03272727],
        [-0.03454545,  0.00727273]])

In [158]:
np.linalg.inv(B).dot(np.linalg.inv(A))

matrix([[ 0.09454545,  0.03272727],
        [-0.03454545,  0.00727273]])

In [160]:
m_eye = np.eye(4)
m_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [162]:
rank = np.linalg.matrix_rank(m_eye)
rank

4

In [163]:
m_eye[3][3] = 0
m_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.]])

In [164]:
np.linalg.matrix_rank(m_eye)

3